name: Add Label

on:
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Label
        uses: actions/labeler@v1
        with:
          labels: 'new-pr'
